TorneioFinal/Presentation/Models/ErrorViewModel.cs
namespace Presentation.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TorneioFinal/Presentation/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Presentation.Models;
using System.Diagnostics;

namespace Presentation.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TorneioFinal/Presentation/Controllers/NewViewsController.cs
using Business.Interfaces;
using Infra.Interfaces;
using Infra.Object;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Presentation.Controllers
{
    public class NewViewsController : Controller
    {
        private readonly IParticipanteService _participanteService;
        private readonly ITorneioService _torneioService;
        public NewViewsController(IParticipanteService participanteService, ITorneioService torneioService)
        {
            _torneioService = torneioService;
            _participanteService = participanteService;
        }


        // GET: NewViewsController
        public ActionResult Index()
        {
            return View(_participanteService.ListandoParticipantes());
        }

        // GET: NewViewsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: NewViewsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NewViewsController/
        [HttpPost]
        public ActionResult EnviaParticipantes(List<int> ids)
        {
            Console.WriteLine(ids);
            List<ParticipanteModel> listaParticipantes = new List<ParticipanteModel>();
            listaParticipantes = _torneioService.TransformaParaListaParticipantes(ids);
            listaParticipantes = _participanteService.OrganizaPorIdade(listaParticipantes);
            Console.WriteLine(listaParticipantes);
            return View("Index");

        }

        // GET: NewViewsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: NewViewsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: NewViewsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: NewViewsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

TorneioFinal/Presentation/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Torneio Final de Lutas</h1>
    <p><a href="https://sbs.t-systems.com.br/gitlab/mercedes/collab/planos-de-desenvolvimento/desenvolvimento-de-software/plano-de-formacao-inicial-backend/-/blob/stable/semanas/12.md">Detalhes do toneio.</a>.</p>
</div>
<hr />

<div>
    <h1>Avaliação</h1>
    <p dir="auto">
        Antes de tudo, leia com atenção e faça o teste com calma, afinal você tem duas semanas para entregar funcionando.
        <br />
        Assim que iniciar a leitura do teste, por favor crie o repositório, para sabermos a data de início.
        <br />
        É importante mencionar que a o período de duas semanas é para a entrega total do projeto, ou seja, no ultimo dia (na apresentação) ele tem que estar funcionando em perfeitas condições. Vale comentar isso para que você faça seu planejamento e consiga entregar na data.
        <br />
        Mesmo que finalize antes do período, revise tudo, faça testes, veja se existe algo para melhorar, enfim, aproveite o tempo que você tem.
        <br />
        Lembrando que apesar de ser um teste, você pode e deve tirar dúvidas a qualquer momento.
        Boa sorte ☘
    </p>
    <hr />
    <h2 dir="auto">
        🥋 Torneio de luta 🥊
    </h2>
    <p>
        O torneio consiste em uma disputa entre 16 lutadores para que seja possível identificar quem é o vencedor com base nas regras definidas.
    </p>
    <hr />
    <h3 dir="auto">
        🌱 Início 🌱
    </h3>
    <p>O torneio inicia com 16 lutadores, sendo que o torneio é somente mata mata e a ordenação das lutas deve ser por idade dos lutadores, do menor para o maior.</p>
    <hr />
    <h3 dir="auto">
        🏹 Oitavas de final 🛡
    </h3>
    <p>Cada luta das oitavas deve ser realizada da seguinte forma: o lutador mais jovem contra o segundo mais jovem e assim sucessivamente.</p>
    <hr />
    <h3>
        ⚔️ Quartas de final ⚔
    </h3>
    <p>O critério das quartas deve seguir o mesmo das oitavas.</p>
    <hr />
    <h3>
        🏅 Semifinal 🏅
    </h3>
    <p>Cada semifinal é realizada entre os vencedores de cada uma das quartas de final, sendo assim o vencedor da luta 1 contra o vencedor da luta 2 e o vencedor da luta 3 contra o vencedor da luta 4.</p>
    <hr />
    <h3>
        🥇 Final 🥈
    </h3>
    <p>A final é disputada pelos vencedores das semifinais.</p>
    <hr />
    <h3>
        🏆 Critério de vitória 🏆
    </h3>
    <p>
        O vencedor é determinado pela maior porcentagem de vitórias, sendo que só é necessário a avaliação do número inteiro, não decimal.
        O cálculo para identificar a porcentagem é: vitórias / total de lutas * 100. Caso haja empate deve ser considerado o critério de desempate.
    </p>
    <hr />
    <h3>
        ⚠️ Critérios de desempate ⚠
    </h3>
    <p>
        O primeiro critério será pela quantidade de artes marciais que o lutador possuí, ou seja, o lutador com maior número é o vencedor.
        Caso a quantidade de artes marciais não seja o suficiente, o segundo critério deve ser pelo número de lutas, sendo assim o lutador com o maior número de lutas é o vencedor.
    </p>
</div>

TorneioFinal/Presentation/Views/NewViews/Index.cshtml
@using Infra.Object
@model IEnumerable<ParticipanteModel>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="bootstrap-5.3.0-alpha1-dist/css/bootstrap.css">
    <link rel="stylesheet" href="~/css/style.css">
    <title>Document</title>

</head>
<body>

    <h1>Seleção dos Participantes</h1>
    <hr />
    <div class="container-fluid">
        <div class="row">
            @foreach (var participante in Model)
            {
                <div id="card-@participante.ParticipanteId" class="col card-inteiro" onclick="selecionarCard(@participante.ParticipanteId)">
                    <div class="frame11">
                        <div class="nomeLutador">
                            @participante.Nome
                        </div>
                        <div class="frame12">
                            <div class="fotoLutador">
                                <img src="imagens/neymar.jfif">
                            </div>
                            <div class="frame9">
                                <div class="idade">
                                    <p>Idade: @participante.Idade</p>
                                </div>
                                <div class="placar">
                                    <p>Placar: @participante.Vitorias V - @participante.Derrotas D</p>
                                </div>
                                <div class="frame10">
                                    <div class="titulos">
                                        <p>Gols: @participante.Gols </p>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            }

        </div>
    </div>

    
    <form class="d-grid gap-2">
        <button id="botaoIniciaTorneio" type="button" onclick="enviarSelecionar()" class="btn btn-primary botaoIniciaTorneio btn-lg">Batalhar</button>
    </form>

    

</body>
</html>

@Html.Hidden("UrlMetodoParaChamar", Url.Action("EnviaParticipantes", "NewViews"))
<script src="~/js/script.js"></script>

TorneioFinal/Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Presentation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Presentation.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Presentation</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NewViews" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Teste 2</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Presentation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>